sudo: required 
services: 
  - docker

before_install: 
  -docker build -t anisdhiyaeddine/react-test -f ./client/Dockerfile.dev ./client

script: 
  -docker run anisdhiyaeddine/react-test npm run test -- --coverage

after_success: 
  - docker build -t anisdhiyaeddine/multi-client ./client
  - docker build -t anisdhiyaeddine/multi-nginx ./nginx 
  - docker build -t anisdhiyaeddine/multi-server ./server
  - docker build -t anisdhiyaeddine/multi-worker ./worker
  # Log in 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push anisdhiyaeddine/multi-client
  - docker push anisdhiyaeddine/multi-nginx 
  - docker push anisdhiyaeddine/multi-server
  - docker push anisdhiyaeddine/multi-worker

